2024-12-16 16:30:29,033 | INFO | "test_challenge" выполнен успешно
2024-12-16 16:30:29,033 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-12-16 16:30:29,035 | WARNING | Traceback (most recent call last):
  File "D:\test\PythonProject4\.venv\tests_12_4.py", line 74, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "D:\test\PythonProject4\.venv\tests_12_4.py", line 14, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-12-16 16:30:29,036 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-12-16 16:30:29,039 | WARNING | Traceback (most recent call last):
  File "D:\test\PythonProject4\.venv\tests_12_4.py", line 63, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "D:\test\PythonProject4\.venv\tests_12_4.py", line 19, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

